site_name: Stream Wallet
site_url: https://docs.streamprotocol.org/wallet
site_description: Everything you need to know about the Stream Wallet.
repo_url: https://github.com/stream-protocol/stream-wallet
edit_uri: ""
site_author: developer@streamprotocol.org

strict: true

nav:
  - Getting Started: 'index.md'
  - Account Management: 'account_management.md'
#    - Switch accounts: 'switch_account.md'
#    - Create a new account: 'new_account.md'
#    - Import existing account: 'import_account.md'
#    - Migrate ETH: 'migrate_eth.md'
  - Deposit Tokens: 'deposit.md'
  - Send Tokens: 'send_tokens.md'
  - Recover Migrated ETH Account: 'migrate_erc20.md'
  - Staking: 'stake.md'
  - Utilities:
    - Address Book: 'address_book.md'
    - Connections: 'connections.md'

theme:
  name: material
  language: en
  palette: # Set light/dark theme button next to the search bar
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/images/logo.png  # Set Stream Logo top left
  favicon: assets/images/favicon.ico  # Set Stream favicon
  features:
    - navigation.instant # Fast page loading
    - navigation.tracking # URL automatically updated with the currently active anchor
#    - navigation.sections # Top level sections will be visible and grouped in sidebar
    - navigation.top # Back-to-top button
    - search.suggest # Completion for the searched word (can be accepted with ->).
    - search.highlight # Highlight all occurrences after following a search result link
    - search.share # Show share button for copying deep link to the current search query and result
#  custom_dir: docs/overrides # Uncomment to enable announcements bar at the top

extra_css:
    - css/my-styles.css

markdown_extensions:
  - admonition # Required by admonitions
  - pymdownx.superfences # Required by admonitions, annotations, tabs. Enables arbitrary nesting of code and content blocks
  - pymdownx.highlight: # Required by code blocks
      anchor_linenums: true
  - pymdownx.inlinehilite # Required by code blocks
  - pymdownx.snippets # Required by code blocks
  - pymdownx.superfences # Required by admonitions, code blocks
  - pymdownx.details # Required by admonitions, code blocks
  - attr_list # Required by annotations
  - md_in_html # Required by annotations
  - pymdownx.tabbed: # Required by tabs
      alternate_style: true
  - tables # # Required by tables

plugins:
  - search # Enables search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://bit.ly/
      name: Stream Protocol on twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/stream_protocol
      name: Stream Protocol on telegram
    - icon: fontawesome/brands/discord
      link: https://bit.ly/
      name: Stream Protocol on discord
    - icon: fontawesome/brands/github
      link: https://bit.ly/
      name: Stream Protocol on githubs
    - icon: fontawesome/brands/reddit
      link: https://bit.ly/
      name: Stream Protocol on reddit
    - icon: fontawesome/brands/youtube
      link: https://bit.ly/
      name: Stream Protocol on youtube
    - icon: fontawesome/brands/linkedin
      link: https://bit.ly/
      name: Stream Protocol on linkedin
